// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: internal/modules/department/department/proto/v1/department.proto

package departmentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Department struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title          string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	DepartmentType string                 `protobuf:"bytes,3,opt,name=department_type,json=departmentType,proto3" json:"department_type,omitempty"`
	Parent         string                 `protobuf:"bytes,4,opt,name=parent,proto3" json:"parent,omitempty"`
	Label          string                 `protobuf:"bytes,5,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Department) Reset() {
	*x = Department{}
	mi := &file_internal_modules_department_department_proto_v1_department_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Department) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Department) ProtoMessage() {}

func (x *Department) ProtoReflect() protoreflect.Message {
	mi := &file_internal_modules_department_department_proto_v1_department_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Department.ProtoReflect.Descriptor instead.
func (*Department) Descriptor() ([]byte, []int) {
	return file_internal_modules_department_department_proto_v1_department_proto_rawDescGZIP(), []int{0}
}

func (x *Department) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Department) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Department) GetDepartmentType() string {
	if x != nil {
		return x.DepartmentType
	}
	return ""
}

func (x *Department) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *Department) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type Departments struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Department          `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Departments) Reset() {
	*x = Departments{}
	mi := &file_internal_modules_department_department_proto_v1_department_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Departments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Departments) ProtoMessage() {}

func (x *Departments) ProtoReflect() protoreflect.Message {
	mi := &file_internal_modules_department_department_proto_v1_department_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Departments.ProtoReflect.Descriptor instead.
func (*Departments) Descriptor() ([]byte, []int) {
	return file_internal_modules_department_department_proto_v1_department_proto_rawDescGZIP(), []int{1}
}

func (x *Departments) GetData() []*Department {
	if x != nil {
		return x.Data
	}
	return nil
}

type PagePack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	TotalRows     int64                  `protobuf:"varint,3,opt,name=total_rows,json=totalRows,proto3" json:"total_rows,omitempty"`
	TotalPages    int32                  `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PagePack) Reset() {
	*x = PagePack{}
	mi := &file_internal_modules_department_department_proto_v1_department_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PagePack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PagePack) ProtoMessage() {}

func (x *PagePack) ProtoReflect() protoreflect.Message {
	mi := &file_internal_modules_department_department_proto_v1_department_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PagePack.ProtoReflect.Descriptor instead.
func (*PagePack) Descriptor() ([]byte, []int) {
	return file_internal_modules_department_department_proto_v1_department_proto_rawDescGZIP(), []int{2}
}

func (x *PagePack) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PagePack) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PagePack) GetTotalRows() int64 {
	if x != nil {
		return x.TotalRows
	}
	return 0
}

func (x *PagePack) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

type DepartmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     string                 `protobuf:"bytes,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Data          *Department            `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepartmentResponse) Reset() {
	*x = DepartmentResponse{}
	mi := &file_internal_modules_department_department_proto_v1_department_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepartmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepartmentResponse) ProtoMessage() {}

func (x *DepartmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_modules_department_department_proto_v1_department_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepartmentResponse.ProtoReflect.Descriptor instead.
func (*DepartmentResponse) Descriptor() ([]byte, []int) {
	return file_internal_modules_department_department_proto_v1_department_proto_rawDescGZIP(), []int{3}
}

func (x *DepartmentResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *DepartmentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DepartmentResponse) GetData() *Department {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DepartmentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DepartmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     string                 `protobuf:"bytes,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Data          []*Department          `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Pagination    *PagePack              `protobuf:"bytes,5,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepartmentsResponse) Reset() {
	*x = DepartmentsResponse{}
	mi := &file_internal_modules_department_department_proto_v1_department_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepartmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepartmentsResponse) ProtoMessage() {}

func (x *DepartmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_modules_department_department_proto_v1_department_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepartmentsResponse.ProtoReflect.Descriptor instead.
func (*DepartmentsResponse) Descriptor() ([]byte, []int) {
	return file_internal_modules_department_department_proto_v1_department_proto_rawDescGZIP(), []int{4}
}

func (x *DepartmentsResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *DepartmentsResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DepartmentsResponse) GetData() []*Department {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DepartmentsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DepartmentsResponse) GetPagination() *PagePack {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type AddDepartmentRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Title            string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	DepartmentTypeId uint32                 `protobuf:"varint,2,opt,name=department_type_id,json=departmentTypeId,proto3" json:"department_type_id,omitempty"`
	ParentId         uint32                 `protobuf:"varint,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AddDepartmentRequest) Reset() {
	*x = AddDepartmentRequest{}
	mi := &file_internal_modules_department_department_proto_v1_department_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDepartmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDepartmentRequest) ProtoMessage() {}

func (x *AddDepartmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_modules_department_department_proto_v1_department_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDepartmentRequest.ProtoReflect.Descriptor instead.
func (*AddDepartmentRequest) Descriptor() ([]byte, []int) {
	return file_internal_modules_department_department_proto_v1_department_proto_rawDescGZIP(), []int{5}
}

func (x *AddDepartmentRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AddDepartmentRequest) GetDepartmentTypeId() uint32 {
	if x != nil {
		return x.DepartmentTypeId
	}
	return 0
}

func (x *AddDepartmentRequest) GetParentId() uint32 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

type ListDepartmentRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Title            string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Department       string                 `protobuf:"bytes,2,opt,name=department,proto3" json:"department,omitempty"`
	DepartmentTypeId uint32                 `protobuf:"varint,3,opt,name=department_type_id,json=departmentTypeId,proto3" json:"department_type_id,omitempty"`
	DepartmentType   string                 `protobuf:"bytes,4,opt,name=department_type,json=departmentType,proto3" json:"department_type,omitempty"`
	ParentId         uint32                 `protobuf:"varint,5,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Parent           string                 `protobuf:"bytes,6,opt,name=parent,proto3" json:"parent,omitempty"`
	Expand           bool                   `protobuf:"varint,7,opt,name=expand,proto3" json:"expand,omitempty"`
	Sort             string                 `protobuf:"bytes,8,opt,name=sort,proto3" json:"sort,omitempty"`
	Order            string                 `protobuf:"bytes,9,opt,name=order,proto3" json:"order,omitempty"`
	Page             int32                  `protobuf:"varint,10,opt,name=page,proto3" json:"page,omitempty"`
	PageSize         int32                  `protobuf:"varint,11,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListDepartmentRequest) Reset() {
	*x = ListDepartmentRequest{}
	mi := &file_internal_modules_department_department_proto_v1_department_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDepartmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDepartmentRequest) ProtoMessage() {}

func (x *ListDepartmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_modules_department_department_proto_v1_department_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDepartmentRequest.ProtoReflect.Descriptor instead.
func (*ListDepartmentRequest) Descriptor() ([]byte, []int) {
	return file_internal_modules_department_department_proto_v1_department_proto_rawDescGZIP(), []int{6}
}

func (x *ListDepartmentRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ListDepartmentRequest) GetDepartment() string {
	if x != nil {
		return x.Department
	}
	return ""
}

func (x *ListDepartmentRequest) GetDepartmentTypeId() uint32 {
	if x != nil {
		return x.DepartmentTypeId
	}
	return 0
}

func (x *ListDepartmentRequest) GetDepartmentType() string {
	if x != nil {
		return x.DepartmentType
	}
	return ""
}

func (x *ListDepartmentRequest) GetParentId() uint32 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *ListDepartmentRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *ListDepartmentRequest) GetExpand() bool {
	if x != nil {
		return x.Expand
	}
	return false
}

func (x *ListDepartmentRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *ListDepartmentRequest) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

func (x *ListDepartmentRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListDepartmentRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

var File_internal_modules_department_department_proto_v1_department_proto protoreflect.FileDescriptor

const file_internal_modules_department_department_proto_v1_department_proto_rawDesc = "" +
	"\n" +
	"@internal/modules/department/department/proto/v1/department.proto\x12\rdepartment.v1\"\x89\x01\n" +
	"\n" +
	"Department\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12'\n" +
	"\x0fdepartment_type\x18\x03 \x01(\tR\x0edepartmentType\x12\x16\n" +
	"\x06parent\x18\x04 \x01(\tR\x06parent\x12\x14\n" +
	"\x05label\x18\x05 \x01(\tR\x05label\"<\n" +
	"\vDepartments\x12-\n" +
	"\x04data\x18\x01 \x03(\v2\x19.department.v1.DepartmentR\x04data\"{\n" +
	"\bPagePack\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"total_rows\x18\x03 \x01(\x03R\ttotalRows\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\x05R\n" +
	"totalPages\"\x94\x01\n" +
	"\x12DepartmentResponse\x12\x1d\n" +
	"\n" +
	"error_code\x18\x01 \x01(\tR\terrorCode\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12-\n" +
	"\x04data\x18\x03 \x01(\v2\x19.department.v1.DepartmentR\x04data\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\xce\x01\n" +
	"\x13DepartmentsResponse\x12\x1d\n" +
	"\n" +
	"error_code\x18\x01 \x01(\tR\terrorCode\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12-\n" +
	"\x04data\x18\x03 \x03(\v2\x19.department.v1.DepartmentR\x04data\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x127\n" +
	"\n" +
	"pagination\x18\x05 \x01(\v2\x17.department.v1.PagePackR\n" +
	"pagination\"w\n" +
	"\x14AddDepartmentRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12,\n" +
	"\x12department_type_id\x18\x02 \x01(\rR\x10departmentTypeId\x12\x1b\n" +
	"\tparent_id\x18\x03 \x01(\rR\bparentId\"\xcc\x02\n" +
	"\x15ListDepartmentRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x1e\n" +
	"\n" +
	"department\x18\x02 \x01(\tR\n" +
	"department\x12,\n" +
	"\x12department_type_id\x18\x03 \x01(\rR\x10departmentTypeId\x12'\n" +
	"\x0fdepartment_type\x18\x04 \x01(\tR\x0edepartmentType\x12\x1b\n" +
	"\tparent_id\x18\x05 \x01(\rR\bparentId\x12\x16\n" +
	"\x06parent\x18\x06 \x01(\tR\x06parent\x12\x16\n" +
	"\x06expand\x18\a \x01(\bR\x06expand\x12\x12\n" +
	"\x04sort\x18\b \x01(\tR\x04sort\x12\x14\n" +
	"\x05order\x18\t \x01(\tR\x05order\x12\x12\n" +
	"\x04page\x18\n" +
	" \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\v \x01(\x05R\bpageSize2\xc8\x01\n" +
	"\x11DepartmentService\x12W\n" +
	"\rAddDepartment\x12#.department.v1.AddDepartmentRequest\x1a!.department.v1.DepartmentResponse\x12Z\n" +
	"\x0eListDepartment\x12$.department.v1.ListDepartmentRequest\x1a\".department.v1.DepartmentsResponseB!Z\x1f./pb/department/v1;departmentv1b\x06proto3"

var (
	file_internal_modules_department_department_proto_v1_department_proto_rawDescOnce sync.Once
	file_internal_modules_department_department_proto_v1_department_proto_rawDescData []byte
)

func file_internal_modules_department_department_proto_v1_department_proto_rawDescGZIP() []byte {
	file_internal_modules_department_department_proto_v1_department_proto_rawDescOnce.Do(func() {
		file_internal_modules_department_department_proto_v1_department_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_modules_department_department_proto_v1_department_proto_rawDesc), len(file_internal_modules_department_department_proto_v1_department_proto_rawDesc)))
	})
	return file_internal_modules_department_department_proto_v1_department_proto_rawDescData
}

var file_internal_modules_department_department_proto_v1_department_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_internal_modules_department_department_proto_v1_department_proto_goTypes = []any{
	(*Department)(nil),            // 0: department.v1.Department
	(*Departments)(nil),           // 1: department.v1.Departments
	(*PagePack)(nil),              // 2: department.v1.PagePack
	(*DepartmentResponse)(nil),    // 3: department.v1.DepartmentResponse
	(*DepartmentsResponse)(nil),   // 4: department.v1.DepartmentsResponse
	(*AddDepartmentRequest)(nil),  // 5: department.v1.AddDepartmentRequest
	(*ListDepartmentRequest)(nil), // 6: department.v1.ListDepartmentRequest
}
var file_internal_modules_department_department_proto_v1_department_proto_depIdxs = []int32{
	0, // 0: department.v1.Departments.data:type_name -> department.v1.Department
	0, // 1: department.v1.DepartmentResponse.data:type_name -> department.v1.Department
	0, // 2: department.v1.DepartmentsResponse.data:type_name -> department.v1.Department
	2, // 3: department.v1.DepartmentsResponse.pagination:type_name -> department.v1.PagePack
	5, // 4: department.v1.DepartmentService.AddDepartment:input_type -> department.v1.AddDepartmentRequest
	6, // 5: department.v1.DepartmentService.ListDepartment:input_type -> department.v1.ListDepartmentRequest
	3, // 6: department.v1.DepartmentService.AddDepartment:output_type -> department.v1.DepartmentResponse
	4, // 7: department.v1.DepartmentService.ListDepartment:output_type -> department.v1.DepartmentsResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_internal_modules_department_department_proto_v1_department_proto_init() }
func file_internal_modules_department_department_proto_v1_department_proto_init() {
	if File_internal_modules_department_department_proto_v1_department_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_modules_department_department_proto_v1_department_proto_rawDesc), len(file_internal_modules_department_department_proto_v1_department_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_modules_department_department_proto_v1_department_proto_goTypes,
		DependencyIndexes: file_internal_modules_department_department_proto_v1_department_proto_depIdxs,
		MessageInfos:      file_internal_modules_department_department_proto_v1_department_proto_msgTypes,
	}.Build()
	File_internal_modules_department_department_proto_v1_department_proto = out.File
	file_internal_modules_department_department_proto_v1_department_proto_goTypes = nil
	file_internal_modules_department_department_proto_v1_department_proto_depIdxs = nil
}
