// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/department-type/": {
            "get": {
                "description": "Returns a list of Deaprtment types",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "department-type"
                ],
                "summary": "Get Department types",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/department/": {
            "get": {
                "description": "Returns a list ofDeaprtment",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "department"
                ],
                "summary": "Get Departments",
                "parameters": [
                    {
                        "type": "string",
                        "name": "department",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "department_type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "departmenttypeid",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "name": "expand",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "parent",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "parentid",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "title",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Response object",
                        "schema": {
                            "$ref": "#/definitions/responses.DepartmentsResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/department/{id}": {
            "get": {
                "description": "Returns a Deaprtment",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "department"
                ],
                "summary": "Get Department",
                "parameters": [
                    {
                        "type": "string",
                        "name": "department",
                        "in": "path"
                    },
                    {
                        "type": "integer",
                        "name": "id",
                        "in": "path"
                    },
                    {
                        "type": "boolean",
                        "name": "expand",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "name": "department",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "departmentId",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "name": "expand",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Response object",
                        "schema": {
                            "$ref": "#/definitions/responses.DepartmentResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "pagination.PagePack": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                },
                "total_rows": {
                    "type": "integer"
                }
            }
        },
        "responses.Department": {
            "type": "object",
            "properties": {
                "departmentType": {},
                "id": {
                    "type": "integer"
                },
                "label": {
                    "type": "string"
                },
                "parent": {},
                "title": {
                    "type": "string"
                }
            }
        },
        "responses.DepartmentResponse": {
            "type": "object",
            "properties": {
                "_error_code": {
                    "type": "string",
                    "example": ""
                },
                "_status": {
                    "type": "string",
                    "example": "success"
                },
                "data": {
                    "$ref": "#/definitions/responses.Department"
                },
                "message": {
                    "type": "string",
                    "example": "null"
                }
            }
        },
        "responses.DepartmentsResponse": {
            "type": "object",
            "properties": {
                "_error_code": {
                    "type": "string",
                    "example": ""
                },
                "_pagination": {
                    "$ref": "#/definitions/pagination.PagePack"
                },
                "_status": {
                    "type": "string",
                    "example": "success"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/responses.Department"
                    }
                },
                "message": {
                    "type": "string",
                    "example": "null"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
